### ISSUE TITLE
CAMERA NOT DICONNECTING AFTER QUAGGA.STOP() CALLED

### ISSUE THREAD

**Issue by BISWAJITABISWAL** [ericblade/quagga2#525] opened 2023-11-21 06:10 UTC
```
import React, { useEffect } from "react";
import config from "./config.json";
import Quagga from "quagga";

const Scanner = (props) => {
const { onDetected } = props;

useEffect(() => {
Quagga.init(config, (err) => {
if (err) {
console.log(err, "error msg");
}

  Quagga.start();
});

//detecting boxes on stream
Quagga.onProcessed(onProcessed);

Quagga.onDetected(detected);

return () => {
    Quagga.offDetected(detected);
  };
}, [onDetected]);

const onProcessed = (result) => {
    var drawingCtx = Quagga.canvas.ctx.overlay,
        drawingCanvas = Quagga.canvas.dom.overlay;

    if (result) {
        if (result.boxes) {
            drawingCtx.clearRect(
                0,
                0,
                Number(drawingCanvas.getAttribute("width")),
                Number(drawingCanvas.getAttribute("height"))
            );
            result.boxes
                .filter(function (box) {
                    return box !== result.box;
                })
                .forEach(function (box) {
                    Quagga.ImageDebug.drawPath(box, { x: 0, y: 1 }, drawingCtx, {
                        color: "green",
                        lineWidth: 2
                    });
                });
        }

        if (result.box) {
            Quagga.ImageDebug.drawPath(result.box, { x: 0, y: 1 }, drawingCtx, {
                color: "#00F",
                lineWidth: 2
            });
        }

        if (result.codeResult && result.codeResult.code) {
            Quagga.ImageDebug.drawPath(
                result.line,
                { x: "x", y: "y" },
                drawingCtx,
                { color: "red", lineWidth: 3 }
            );
        }
    }
}
const detected = (result) => {
if (result.codeResult.code.toLowerCase().includes("assetid")) {
Quagga.offDetected(detected);
onDetected(result.codeResult.code);
}
};

useEffect(() => {
return () => {
Quagga.offProcessed(onProcessed);
Quagga.offDetected(detected);
Quagga.stop();
}
}, []);

return (
// If you do not specify a target,
// QuaggaJS would look for an element that matches
// the CSS selector #interactive.viewport

);
};
export default Scanner;
```

My issue is when the component is destroyed the camera is not turing off, even if i do stop(). I tried all possible ways but still none of them work

**Comment by ericblade** [comment] 2023-11-22 04:15
I made a bit of an attempt to try to figure out what's going on here, but the formatting of this code is just completely illegible... so I pasted it into javascript, and this code just doesn't run.  Could you please reformat it and fix the errors and try again?

**Comment by usamahassankhan** [comment] 2023-12-22 08:20
Getting same error ,did you find solution?

**Comment by ericblade** [comment] 2023-12-22 16:52
@usamahassankhan if you're using the same code as @BISWAJITABISWAL it's because their code doesn't even parse, so it's never running the stop.

**Comment by ericblade** [comment] 2023-12-27 06:03
Closing due to no further input

**Closed by ericblade** 2023-12-27 06:03 UTC

**Comment by gbrocha** [comment] 2024-07-31 22:37
Getting the same issue here. The camera does not disconnect when calling Quagga.stop() or even calling Quagga.CameraAccess.release(). 
Chrome still presenting the message "This tab is using your camera"
Is someone having the same issue?

**Comment by ericblade** [comment] 2024-08-01 07:03
I would say the best way to diagnose it is to put a breakpoint on your call to stop, but also put a breakpoint on your call to start -- what I found was that I had to do some slight reorganization to how some things were handled in my app, because first it wasn't hitting the stop call, and then after that was fixed, the app was hitting the start call again, and then the component would be unmounted without calling stop again.   I think it was some sort of weird thing happening because of the way that I animated the opening and closing part, because my camera div slides open and closed .. so it was spamming the start call.  

If you are certain that stop is being hit, and you're not doing another start right after, then we have a problem to look into here, or perhaps in the browser itself.

**Comment by gbrocha** [comment] 2024-08-01 23:28
After some hours of debugging, I realized this bug was happening only on local environment

**Comment by ericblade** [comment] 2024-08-07 03:46
If you figure out the cause, drop in and post it, so we have more suggestions for when it inevitably happens to someone else :) 

I'm reasonably certain that it's not a problem with the library itself, but I might be able to mitigate it in the library, as I did when I added async to the stop/start, so we could know when the operation had completed by awaiting it.

**Comment by gbrocha** [comment] 2024-08-07 16:54
I am not sure about the root cause, but I think it was because I was using a reverse proxy to be possible to access the local environment with https (I needed it to access some authentication cookies). 
Since the browser was not recognizing the fake certificate, the app was being opened as an insecure site. Maybe this insecure mode was presenting some strange behavior, I guess.

**Comment by Will-at-FreedomDev** [comment] 2024-11-08 20:04
I also have this issue, however every environment. I'm not sure what the difference is on my end, but I have to explicitly call
```js
Quagga.cameraAccess.getActiveTrack().stop(); // <----- Should not be necessary, but it fixes the issue.
Quagga.stop();
```

**Comment by ericblade** [comment] 2024-11-14 23:46
@Will-at-FreedomDev anything showing up in console?  

stop() calls CameraAccess.release() which does

```
        const tracks = streamRef && streamRef.getVideoTracks();
        if (QuaggaJSCameraAccess.requestedVideoElement !== null) {
            QuaggaJSCameraAccess.requestedVideoElement.pause();
        }
        return new Promise<void>((resolve) => {
            setTimeout(() => {
                if (tracks && tracks.length) {
                    tracks.forEach((track) => track.stop());
                }
                streamRef = null;
                QuaggaJSCameraAccess.requestedVideoElement = null;
                resolve();
            }, 0);
        });
```
which seems like it would be more extensive, and cover pretty much any possible thing running on it... but... maybe your solution is all that's necessary, and we're just doing way more than needed in there.

**Comment by Will-at-FreedomDev** [comment] 2024-11-19 14:23
Hey @ericblade , sorry nothing in the console. Just silently keeps ahold of the camera.

Since you shared some code, I took a look at the library. It seems pretty straightforward to me and it seems like calling `Quagga.stop()` should really release the camera and my workaround logically doesn't seem to be necessary (but it is).

If I end up working on that project again, I'll see if I can uncover anything else by digging a little deeper. 

My hunch is maybe [this if statement](https://github.com/ericblade/quagga2/blob/6c35b66f274b4343930095d30c50a18edae220af/src/quagga/quagga.ts#L269C9-L269C105) in the `stop()` isn't resolving as true maybe.... I'll comment back here if I end up looking at it again.

**Comment by Will-at-FreedomDev** [comment] 2024-12-03 16:57
It appears that this issue is still present for iPhone 15 v17.3 Safari users. I'm going to look into this some more and can report back if I find out anything worthwhile.

**Comment by Will-at-FreedomDev** [comment] 2024-12-03 20:07
@ericblade Looks like this one is an ID10T error :)

I called `Quagga.init` more than one time. The only issue with doing this is that the camera "in use" status doesn't disappear on it's own. I'm not sure why this was only an issue with Safari (after my workaround) but simply calling `Quagga.stop()` before re-initializing resolves everything.
