### ISSUE TITLE
Not work with Pacejs

### ISSUE THREAD

**Issue by anhchungite** [ericblade/quagga2#147] opened 2020-03-04 01:58 UTC
My app using PaceJS (https://github.hubspot.com/pace/docs/welcome/)
If I remove PaceJS from the my app, It's work.

**Comment by ericblade** [comment] 2020-03-04 05:37
At the very least, please provide a code sample and if there's any console errors.  Thanks!

**Comment by anhchungite** [comment] 2020-03-06 02:12
> At the very least, please provide a code sample and if there's any console errors. Thanks!


Unfortunately, it does not cause errors.
But the `Quagga.decodeSingle` function does not work.

**Comment by ericblade** [comment] 2020-06-15 23:29
I don't really have enough information to be able to proceed here, I don't know anything about Pace, I have no idea what would be causing it to just not work, and no sample has been produced.

**Comment by petebr** [comment] 2021-01-08 16:48
Good call, I have `pace,js` enabled and call to `decodeSingle` failed to call back - no errors. Disable `pace.js` made it work.

**Comment by ericblade** [comment] 2021-01-08 23:09
If someone can show me some code, then I can take a poke at it, and see if I see any obvious reason why.  You can dupe my codepen here, if you want https://codepen.io/ericblade/pen/yLaVoWy  that's just a minimal startup of quagga there right now.  Add whatever this pace.js is, and i'll have a look.

What I see looking through what I think is the module (automatic progress bars, right?) is that it replaces a bunch of browser functionality, so if i can trace that down, and see where it's breaking.. if it's on quagga, i'll try to fix, or see if it's on pace to fix it

**Comment by petebr** [comment] 2021-01-11 11:01
I have tried to replicate my use case, which is a `decodeSingle` on a static image with `pace.js` enabled, but it still works.

[https://codepen.io/petebr/pen/OJRoOEr](https://codepen.io/petebr/pen/OJRoOEr)

Will need more time to compare why it's different from my project, maybe I've set pace up wrong?

**Comment by petebr** [comment] 2021-01-11 13:44
I've updated `pace.js` to current version 1.2.3 in my project and it's working. So I'm happy the issue is solved for me.

**Comment by ericblade** [comment] 2021-01-11 20:58
great to hear! 

@anhchungite i'm going to presume this is fixed in later versions of pace, and close.  please re-open and post some example if you have further input

**Closed by ericblade** 2021-01-11 20:58 UTC
